django_project_tbc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('market.urls', namespace='market'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/urls.py
from django.urls import path
from market.views import get_books, get_book, get_authors, get_author, index


app_name = 'market'
urlpatterns = [
    path('books/', get_books, name='get_books'),
    path('books/<int:book_id>', get_book, name='get_book'),
    path('authors/', get_authors, name='get_authors'),
    path('authors/<int:author_id>', get_author, name='get_author'),
    path('', index, name='index')
]

market/models.py
from django.db import models
from market.choice import BOOK_CATEGORIES, COVER_CHOICES
from django.utils.translation import gettext_lazy as _


class Author(models.Model):
    first_name = models.CharField(_('first name'), max_length=100)
    last_name = models.CharField(_('last name'), max_length=100)
    nationality = models.CharField(_('nationality'), max_length=100)
    age = models.IntegerField(_('age'))

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = _('author')
        verbose_name_plural = _('authors')


class Book(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name=_('author name'))
    name = models.CharField(_('book name'), max_length=150)
    page_count = models.IntegerField(_('page count'))
    cover = models.CharField(_('cover'), max_length=30, choices=COVER_CHOICES)
    price = models.DecimalField(_('price'), max_digits=10, decimal_places=2)
    image = models.ImageField(_('image path'), upload_to='book_images/')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('book')
        verbose_name_plural = _('books')


class Category(models.Model):
    books = models.ManyToManyField(Book, verbose_name=_('books'))
    name = models.CharField(_('genre'), max_length=30, choices=BOOK_CATEGORIES)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')

market/views.py
from django.shortcuts import render, get_object_or_404
from market.models import Book, Author
from django.http import JsonResponse, HttpResponse
from django.core.serializers import serialize
from market.serializers import CustomBookSerializer
from django.core.paginator import Paginator
from django.db.models import Q
import json


def get_books(request):
    books = Book.objects.defer('image')
    books_json = CustomBookSerializer().serialize(
        books, ensure_ascii=False, fields=['name', 'author', 'category', 'page_count', 'price']
    )

    return HttpResponse(books_json,  content_type='application/json', status=200)


def get_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    categories = book.category_set.all()

    return render(request, 'market/books/details.html', {'book': book, 'categories': categories})


def get_authors(request):
    authors = Author.objects.all()
    authors_json = serialize('json', authors)

    return HttpResponse(authors_json, content_type='application/json', status=200)


def get_author(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    books = author.book_set.only('name')
    books_data = serialize('json', books, fields=['name'])

    author_item = {
        'first_name': author.first_name,
        'last_name': author.last_name,
        'nationality': author.nationality,
        'age': author.age,
        'books': json.loads(books_data)
    }

    return JsonResponse(author_item, status=200)


def index(request):
    if request.GET.get('filter'):
        filter_property: str = request.GET.get('filter')
        books = Book.objects.filter(
            Q(name__icontains=filter_property) |
            Q(author__first_name__icontains=filter_property.split(' ')[0]) |
            Q(author__last_name__icontains=filter_property.split(' ')[1:])
        )
    else:
        books = Book.objects.all()
    paginator = Paginator(books, 3)
    page_num = int(request.GET.get('page', 1))
    page = paginator.get_page(page_num)

    return render(request, 'market/index.html', {'page': page})

market/templates/market/books/details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book - {{ book.name }}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'market/style.css' %}">
    <link rel="stylesheet" href="{% static 'market/details.css' %}">
</head>
<body>
    <h1>Book Details</h1>
    <div class="details-cont">
        <img class="details-cont-img" src="{{ book.image.url }}" alt="{{ book.name }} image.">
        <div class="details-cont-body">
            <h2 class="book-name">{{ book.name }}</h2>
            <p><span class="param-title">author:</span> {{ book.author }}</p>
            <p><span class="param-title">categories:</span>
                {% for category in categories %}
                    {{ category }}{% if not forloop.last %},{% endif %}
                {% endfor %}
            </p>
            <p><span class="param-title">page_count:</span> {{ book.page_count }}</p>
            <p><span class="param-title">price:</span> {{ book.price }}</p>
            <a class="back-btn" href="{% url 'market:index' %}">back</a>
        </div>
    </div>
</body>
</html>

market/templates/market/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TBC Bookstore</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'market/style.css' %}">
    <link rel="stylesheet" href="{% static 'market/index.css' %}">
</head>
<body>
    <h1><span class="tbc-span">TBC</span> Bookstore</h1>
    <h2>Books</h2>
    <form method="GET" class="search-form">
        <div class="input-cont">
            <label class="search-bar-label" for="searchFilter">Search Books</label>
            <input class="search-bar" type="text" id="searchFilter" name="filter">
        </div>
        <button class="search-form-btn">Search</button>
    </form>
    <div class="books-cont">
        <div class="books-list">
            {% for book in page.object_list %}
                <div class="books-list-item">
                    <a href="{% url "market:get_book" book.pk %}">
                        <img src="{{ book.image.url }}" alt="{{ book.name }} image">
                    </a>
                    <div class="books-list-item-body">
                        <p>{{ book.name }}</p>
                        <p>{{ book.author }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="pagination-cont">
            {% if page.has_previous %}
                <a class="pagination-btn" href="{% url "market:index" %}?page={{ page.previous_page_number }}{% if request.GET.filter %}&filter={{ request.GET.filter }}{% endif %}">Prev</a>
            {% else %}
                <a class="pagination-btn" disabled>Prev</a>
            {% endif %}

            <span class="current">Page {{ page.number }} of {{ page.paginator.num_pages }}</span>

            {% if page.has_next %}
                <a class="pagination-btn" href="{% url "market:index" %}?page={{ page.next_page_number }}{% if request.GET.filter %}&filter={{ request.GET.filter }}{% endif %}">Next</a>
            {% else %}
                <a class="pagination-btn" disabled>Next</a>
            {% endif %}
        </div>
    </div>
</body>
</html>